"""Adiciona coluna avatar na tabela usuario

Revision ID: 93783e34aa83
Revises: 
Create Date: 2025-01-11 11:45:57.933409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93783e34aa83'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###
